In [1]:
import pandas as pd
from sqlalchemy import create_engine
from password import password

In [2]:
game_penalties = "data/game_penalties.csv"
game_penalties_df = pd.read_csv(game_penalties)
game_penalties_df.head(5)

          play_id penaltySeverity  penaltyMinutes
0   2016020045_41           Minor               2
1  2016020045_101           Minor               2
2  2016020045_134           Minor               2
3  2016020045_174           Minor               2
4  2016020045_189           Minor               2

In [3]:
game_skater_stats = "data/game_skater_stats.csv"
game_skater_stats_df = pd.read_csv(game_skater_stats)
game_skater_stats_df.head(5)

,game_id,player_id,team_id,timeOnIce,assists,goals,shots,hits,powerPlayGoals,powerPlayAssists,...,faceoffTaken,takeaways,giveaways,shortHandedGoals,shortHandedAssists,blocked,plusMinus,evenTimeOnIce,shortHandedTimeOnIce,powerPlayTimeOnIce
0,2016020045,8468513,4,955,1,0,0,2.0,0,0,...,0,1.0,1.0,0,0,1.0,1,858,97,0
1,2016020045,8476906,4,1396,1,0,4,2.0,0,0,...,0,1.0,2.0,0,0,2.0,0,1177,0,219
2,2016020045,8474668,4,915,0,0,1,1.0,0,0,...,0,2.0,0.0,0,0,0.0,-1,805,0,110
3,2016020045,8473512,4,1367,3,0,0,0.0,0,2,...,27,0.0,0.0,0,0,0.0,-1,1083,19,265
4,2016020045,8471762,4,676,0,0,3,2.0,0,0,...,0,0.0,1.0,0,0,0.0,-1,613,63,0

In [4]:
engine = create_engine(f'postgresql://postgres:{password}@localhost:5432/hockey_db')

engine.table_names()

['game_penalties', 'game_skater_stats']

In [5]:
game_penalties_df.to_sql(
    name='game_penalties',
    schema = 'public',
    con = engine,
    if_exists = 'append',
    index = False
)

In [ ]:
game_skater_stats_df.to_sql(
    name = "game_skater_stats",
    schema = 'public',
    con = engine,
    if_exists = 'append',
    index = False
    )